# Generated by Django 4.0.10 on 2023-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizardmisc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DustyBotCommands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
